Cast to strptime
AMF-FLX/AMF-BASE-QAQC pull request #30
Opened 2023-05-23 13:59 UTC by toanngosy

Malformed timestamp failed to catch at this [line](https://github.com/AMF-FLX/AMF-BASE-QAQC/blob/develop/processing/timestamp_checks.py#L195). We don't catch the error when we can't cast the last element of TIMESTAMP_START.
The solution uses the function `cast_as_datetime()` from the `ts_util` to cast the timestamp string.
Fixes Issue #23

## PR Self Evaluation

- [x] I have reviewed my code to check that it contains no sensitive information.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests or modified existing tests that prove my fix is effective or that my feature works
- [x] Existing unit tests pass locally with my changes

2023-05-23 14:00 UTC, toanngosy commented
I added the test for `check_timestamp_format` where we have a bad timestamp at various positions in `TIMESTAMP_START` and `TIMESTAMP_END`.
I added some bad files related to timestamp issues (index 75 to the end) into `file_check_expected_issues_ts3.csv` and changed `run_upload_check_manual_tests.py` so it works with the current test folder structure. 
All checks from `run_upload_check_manual_tests.py` are broken because in `DataReader.read_single_file()` we no longer have `fname= and checklog=`, so I make the change here to make it works as well.

2023-05-24 11:01 UTC, dschristianson requested changes
Hi @toanngosy. Thanks for this work, especially for updating the manual testing helper files!

Some requested changes inline. 

Also, a request to change the tests as follows:
- The unit tests are fine. I'd like to see the case we observed included in the tests. I.e., 000000 for DDHHMM. See the #23 for more details. 
- For the test file for the end-2-end tests, please include just one file that has the observed case. 

The idea is that we catch all the variants of malformed timestamp in the unit tests, and have a representative case for manual end-2-end. Otherwise checking every variant in the manual tests becomes unmanageable.

2023-05-24 14:15 UTC, toanngosy commented on processing/timestamp_checks.py
> +        if last_ts_start and last_ts_start > self.current_date:
This is from function `check_forward_filled_timestamps()`, is called at the end of `driver()`, so at this point the data already has `ts_valid=True`. So I think we can safely assume that the timestamp here is always valid.

2023-05-26 18:45 UTC, dschristianson commented on processing/timestamp_checks.py
> +        if last_ts_start and last_ts_start > self.current_date:
Great. Then small suggestion to change new line 196 to
`if last_ts_start > self.current_date:`
As is, it implies that there is a case in which last_ts_start is None.

2023-05-26 18:47 UTC, dschristianson commented
Thanks for addressing my comments, @toanngosy. Please rebase with the develop branch as I just merged in the other PR. Thanks!

2023-05-26 19:44 UTC, toanngosy commented
> Thanks for addressing my comments, @toanngosy. Please rebase with the develop branch as I just merged in the other PR. Thanks!

I just rebased this PR

2023-05-30 21:39 UTC, dschristianson requested changes
Hi @toanngosy. Looking good! Please have a look at my last comment from Friday. New line 196 in the timestamp_check.py module.

2023-05-30 21:49 UTC, toanngosy commented
Thanks, Danielle, I missed that comment. The new commit addressed that.

2023-05-31 11:51 UTC, dschristianson approved these changes
Thanks, @toanngosy!

2023-05-31 11:52 UTC, merged